#!/usr/bin/env python3
"""Writes tools/unicode_classes.py: the Unicode classes the tokenizer's pre-tokenizer pattern uses, as plain ranges.

The pattern (QWEN35_PATTERN in strata_tokenizer.py, llama.cpp's own for the Qwen3.5 family) is written with `\\p{L}`,
`\\p{N}`, `\\p{M}` and `\\s`, which the standard library's `re` does not have.  strata_tokenizer.py turns them into
character classes built from these ranges, so the server needs nothing but Python.  The ranges are fixed in the file
rather than read from the running Python's `unicodedata`, so a tokenizer on Python 3.8 splits text exactly like one
on 3.13: the table is the one the `regex` module has, at the Unicode version it ships.

    python tools/gen_unicode_classes.py          # needs `regex` (only this script does); rewrites unicode_classes.py
    python tools/gen_unicode_classes.py --check  # exits 1 when the file is not what the installed `regex` gives

serve/test_tokenizer_classes.py runs the check as a test when `regex` is installed.
"""
import argparse
import pathlib
import sys
import unicodedata

OUT = pathlib.Path(__file__).resolve().with_name("unicode_classes.py")
CLASSES = {"L": r"\p{L}", "M": r"\p{M}", "N": r"\p{N}", "s": r"\s"}


def ranges_of(pattern):
    import regex
    rx = regex.compile(pattern)
    out = []
    start = None
    for cp in range(0x110000):
        ok = rx.fullmatch(chr(cp)) is not None
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def render():
    import regex
    lines = [
        'r"""Generated by tools/gen_unicode_classes.py - do not edit.',
        "",
        "The Unicode classes of the tokenizer's pre-tokenizer pattern as (first, last) code point ranges, taken from the",
        "`regex` module (%s; the generating Python's unicodedata is Unicode %s).  L, M, N: `\\p{L}`, `\\p{M}`, `\\p{N}`." % (
            regex.__version__, unicodedata.unidata_version),
        's: `\\s` as the `regex` module has it (Unicode White_Space).',
        '"""',
        "",
        "CLASSES = {",
    ]
    for name, pattern in CLASSES.items():
        rs = ranges_of(pattern)
        lines.append("    %r: (" % name)
        row = []
        for lo, hi in rs:
            row.append("(0x%X, 0x%X)," % (lo, hi))
            if len(row) == 5:
                lines.append("        " + " ".join(row))
                row = []
        if row:
            lines.append("        " + " ".join(row))
        lines.append("    ),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("tools/unicode_classes.py is not what the installed `regex` gives; run tools/gen_unicode_classes.py")
            return 1
        print("tools/unicode_classes.py is current")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote", OUT, "(%d bytes)" % len(text))
    return 0


if __name__ == "__main__":
    sys.exit(main())
